FROM node:18 AS builder
WORKDIR /app

# install deps
COPY package.json package-lock.json* ./
RUN npm ci --silent

# build
# Accept build-time API token for React
ARG REACT_APP_API_TOKEN=""
ENV REACT_APP_API_TOKEN=${REACT_APP_API_TOKEN}
COPY . .
RUN npm run build

FROM nginx:stable-alpine
# copy built assets
COPY --from=builder /app/build /usr/share/nginx/html

# custom nginx config
COPY docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
